name: dino_vpn
description: v2ray clinet.
publish_to: 'none' 
version: 1.5.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  avatar_glow: ^2.0.2
  circularbox: ^1.1.1+1
  roundcheckbox: ^2.0.5
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  progress_loading_button: ^2.0.2
  provider: ^6.0.5
  dart_ipify: ^1.1.1
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1
  window_size:
      git:
        url: https://github.com/google/flutter-desktop-embedding.git
        path: plugins/window_size
  salomon_bottom_bar:
  webview_flutter: ^4.2.2
  is_first_run: ^1.0.0
  dynamic_library: ^0.9.0
  path_provider: ^2.1.1
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  flutter_expandable_fab: ^2.0.0
  qr_flutter: ^4.1.0
  http: ^1.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
